### PR TITLE
Checksum verified after download

### LINKED ISSUE #10: Verify checksum after download
@gwaygenomics noted this error https://github.com/broadinstitute/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/issues/5#issuecomment-570281677, which is likely because the file was corrupted. Our current workflow to restore does not include instructions to verify checksum

### PR DESCRIPTION
**Pull request by shntnu**
Closes #10

### CODE REVIEW

**Comment by shntnu** [comment]
The script and instructions have been updated to download md5. 

I have started the restore of one file

```sh
$ ./glacier_restore.sh --project_name 2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad --batch_id 2016_04_01_a549_48hr_batch1 --plate_id SQ00015223 --get_backend --check_status
Get backend ...
{
    "Restore": "ongoing-request=\"true\"",
    "AcceptRanges": "bytes",
    "ContentType": "application/x-md5",
    "LastModified": "Sun, 17 Jun 2018 01:33:40 GMT",
    "ContentLength": 149,
    "VersionId": "XI6tiYnQwvZ6lH4IbKtymMbOglpJ9qKL",
    "ETag": "\"ebda9def8426b17f8b4205dd76ffedd4\"",
    "StorageClass": "GLACIER",
    "Metadata": {}
}
{
    "Restore": "ongoing-request=\"true\"",
    "AcceptRanges": "bytes",
    "ContentType": "application/x-tar",
    "LastModified": "Sun, 17 Jun 2018 01:32:08 GMT",
    "ContentLength": 6788529078,
    "VersionId": "xR9HlWn6HXi49wfFfjJIinBxPCS2htKr",
    "ETag": "\"43d98318c116f4d25d41ae88ac165b1f-810\"",
    "StorageClass": "GLACIER",
    "Metadata": {}
}
Download:s3://imaging-platform-cold/imaging_analysis/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/plates/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad_2016_04_01_a549_48hr_batch1_SQ00015223_backend.tar.gz
MD5Download:s3://imaging-platform-cold/imaging_analysis/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/plates/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad_2016_04_01_a549_48hr_batch1_SQ00015223_backend.md5
```

Once restored, possibly in a few hours, add instructions to verify md5.

**Comment by shntnu** [comment]
> Once restored, possibly in a few hours, add instructions to verify md5.

@gwaygenomics Can you give this a shot? I think your files in https://github.com/broadinstitute/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/issues/5#issuecomment-570281677 might have been corrupted but there's currently no way of knowing

**Comment by gwaygenomics** [comment]
> Can you give this a shot?

Are there instructions somewhere on how to use? Sorry if I'm overlooking something obvious!

**Comment by shntnu** [comment]
> Are there instructions somewhere on how to use? Sorry if I'm overlooking something obvious!

Looks like you're all set as of https://github.com/broadinstitute/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/issues/5#issuecomment-570780566 so you can ignore this (I'll handle this issue)

**Pull request merged**
